// <auto-generated />
using System;
using IdsServer.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IdsServer.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250124211011_InitialCreate2")]
    partial class InitialCreate2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("IdsServer.Database.Models.Basket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("HookUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastUpdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawBasket")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Basket", (string)null);
                });

            modelBuilder.Entity("IdsServer.Database.Models.FakeArticle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ArticleNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ListPrice")
                        .HasPrecision(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FakeArticle", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("fd7aed7f-7ef6-409b-a34f-da22a663aae5"),
                            ArticleNumber = "1085922350000",
                            Currency = "EUR",
                            Description = "Bacon ipsum dolor amet filet mignon shank drumstick sausage, cow sirloin rump corned beef tongue chicken kevin. Salami ham corned beef, kevin cow fatback bresaola sausage jerky hamburger tail capicola. Biltong pork jerky fatback venison pig. Jowl strip steak short ribs ham spare ribs, swine jerky pork belly frankfurter alcatra pork picanha boudin tongue beef. Doner meatloaf ribeye prosciutto tri-tip capicola. Landjaeger ham hock swine corned beef ground round tail biltong salami pastrami pork belly. Jerky shank landjaeger biltong, doner porchetta chicken pancetta shankle shoulder sausage pork chop corned beef burgdoggen.",
                            ImageUrl = "https://placehold.co/500x400",
                            ListPrice = 237.99m,
                            Name = "filet mignon shank drumstick",
                            Price = 200.67m
                        },
                        new
                        {
                            Id = new Guid("c3e89e64-9f00-4dc0-8adf-55223601d9f6"),
                            ArticleNumber = "24485918350056",
                            Currency = "EUR",
                            Description = "Bresaola picanha landjaeger prosciutto ball tip burgdoggen pork belly. Swine ham hock salami spare ribs turducken venison tri-tip biltong t-bone prosciutto jowl beef ribs turkey beef shank. Hamburger picanha strip steak, pork chop buffalo tenderloin corned beef ball tip jowl sirloin bacon pork. Ribeye kevin shankle, tongue short loin beef ribs pancetta tenderloin tri-tip short ribs. Strip steak brisket rump, boudin ham landjaeger chuck spare ribs.",
                            ImageUrl = "https://placehold.co/500x400",
                            ListPrice = 123.00m,
                            Name = "Bresaola picanha landjaeger",
                            Price = 100.12m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
