//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.itek.de/Shop-Anbindung/Warenkorb/")]
[System.Xml.Serialization.XmlRootAttribute("Warenkorb", Namespace="http://www.itek.de/Shop-Anbindung/Warenkorb/", IsNullable=false)]
public partial class typeWarenkorb {
    
    private typeWarenkorbInfo warenkorbInfoField;
    
    private typeOrder orderField;
    
    /// <remarks/>
    public typeWarenkorbInfo WarenkorbInfo {
        get {
            return this.warenkorbInfoField;
        }
        set {
            this.warenkorbInfoField = value;
        }
    }
    
    /// <remarks/>
    public typeOrder Order {
        get {
            return this.orderField;
        }
        set {
            this.orderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.itek.de/Shop-Anbindung/Warenkorb/")]
public partial class typeWarenkorbInfo {
    
    private System.DateTime dateField;
    
    private System.DateTime timeField;
    
    private typeWarenkorbInfoRueckgabeKZ rueckgabeKZField;
    
    private typeWarenkorbInfoVersion versionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime Date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="time")]
    public System.DateTime Time {
        get {
            return this.timeField;
        }
        set {
            this.timeField = value;
        }
    }
    
    /// <remarks/>
    public typeWarenkorbInfoRueckgabeKZ RueckgabeKZ {
        get {
            return this.rueckgabeKZField;
        }
        set {
            this.rueckgabeKZField = value;
        }
    }
    
    /// <remarks/>
    public typeWarenkorbInfoVersion Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.itek.de/Shop-Anbindung/Warenkorb/")]
public enum typeWarenkorbInfoRueckgabeKZ {
    
    /// <remarks/>
    Warenkorbrückgabe,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Warenkorbrückgabe mit Bestellung")]
    WarenkorbrückgabemitBestellung,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.itek.de/Shop-Anbindung/Warenkorb/")]
public enum typeWarenkorbInfoVersion {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("2.5")]
    Item25,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.itek.de/Shop-Anbindung/Warenkorb/")]
public partial class typeRohstoffanteil {
    
    private CodelisteRohstoffe rohstoffField;
    
    private bool rohstoffFieldSpecified;
    
    private decimal gewichtsanteilswertField;
    
    private bool gewichtsanteilswertFieldSpecified;
    
    private CodelisteMengeneinheit gewichtsanteilseinheitField;
    
    private bool gewichtsanteilseinheitFieldSpecified;
    
    private decimal basiswertField;
    
    private bool basiswertFieldSpecified;
    
    private CodelisteMengeneinheit basiseinheitField;
    
    private bool basiseinheitFieldSpecified;
    
    private decimal basisnotierungField;
    
    private bool basisnotierungFieldSpecified;
    
    private decimal notierungAktuellField;
    
    private bool notierungAktuellFieldSpecified;
    
    /// <remarks/>
    public CodelisteRohstoffe Rohstoff {
        get {
            return this.rohstoffField;
        }
        set {
            this.rohstoffField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool RohstoffSpecified {
        get {
            return this.rohstoffFieldSpecified;
        }
        set {
            this.rohstoffFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal Gewichtsanteilswert {
        get {
            return this.gewichtsanteilswertField;
        }
        set {
            this.gewichtsanteilswertField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool GewichtsanteilswertSpecified {
        get {
            return this.gewichtsanteilswertFieldSpecified;
        }
        set {
            this.gewichtsanteilswertFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public CodelisteMengeneinheit Gewichtsanteilseinheit {
        get {
            return this.gewichtsanteilseinheitField;
        }
        set {
            this.gewichtsanteilseinheitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool GewichtsanteilseinheitSpecified {
        get {
            return this.gewichtsanteilseinheitFieldSpecified;
        }
        set {
            this.gewichtsanteilseinheitFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal Basiswert {
        get {
            return this.basiswertField;
        }
        set {
            this.basiswertField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BasiswertSpecified {
        get {
            return this.basiswertFieldSpecified;
        }
        set {
            this.basiswertFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public CodelisteMengeneinheit Basiseinheit {
        get {
            return this.basiseinheitField;
        }
        set {
            this.basiseinheitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BasiseinheitSpecified {
        get {
            return this.basiseinheitFieldSpecified;
        }
        set {
            this.basiseinheitFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal Basisnotierung {
        get {
            return this.basisnotierungField;
        }
        set {
            this.basisnotierungField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BasisnotierungSpecified {
        get {
            return this.basisnotierungFieldSpecified;
        }
        set {
            this.basisnotierungFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal NotierungAktuell {
        get {
            return this.notierungAktuellField;
        }
        set {
            this.notierungAktuellField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NotierungAktuellSpecified {
        get {
            return this.notierungAktuellFieldSpecified;
        }
        set {
            this.notierungAktuellFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.itek.de/Shop-Anbindung/Warenkorb/")]
public enum CodelisteRohstoffe {
    
    /// <remarks/>
    AL,
    
    /// <remarks/>
    PB,
    
    /// <remarks/>
    CR,
    
    /// <remarks/>
    AU,
    
    /// <remarks/>
    CD,
    
    /// <remarks/>
    CU,
    
    /// <remarks/>
    MG,
    
    /// <remarks/>
    NI,
    
    /// <remarks/>
    PL,
    
    /// <remarks/>
    AG,
    
    /// <remarks/>
    W,
    
    /// <remarks/>
    ZN,
    
    /// <remarks/>
    SN,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.itek.de/Shop-Anbindung/Warenkorb/")]
public enum CodelisteMengeneinheit {
    
    /// <remarks/>
    CMQ,
    
    /// <remarks/>
    CMK,
    
    /// <remarks/>
    CMT,
    
    /// <remarks/>
    DZN,
    
    /// <remarks/>
    GRM,
    
    /// <remarks/>
    HLT,
    
    /// <remarks/>
    KGM,
    
    /// <remarks/>
    KTM,
    
    /// <remarks/>
    LTR,
    
    /// <remarks/>
    MMT,
    
    /// <remarks/>
    MTK,
    
    /// <remarks/>
    MTQ,
    
    /// <remarks/>
    MTR,
    
    /// <remarks/>
    PR,
    
    /// <remarks/>
    PCE,
    
    /// <remarks/>
    SET,
    
    /// <remarks/>
    TNE,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.itek.de/Shop-Anbindung/Warenkorb/")]
public partial class typeRefItems {
    
    private string[] customerField;
    
    private string[] customerSubNoField;
    
    private string[] supplierField;
    
    private string[] supplierSubNoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Customer", DataType="normalizedString")]
    public string[] Customer {
        get {
            return this.customerField;
        }
        set {
            this.customerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CustomerSubNo", DataType="normalizedString")]
    public string[] CustomerSubNo {
        get {
            return this.customerSubNoField;
        }
        set {
            this.customerSubNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Supplier", DataType="normalizedString")]
    public string[] Supplier {
        get {
            return this.supplierField;
        }
        set {
            this.supplierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SupplierSubNo", DataType="normalizedString")]
    public string[] SupplierSubNo {
        get {
            return this.supplierSubNoField;
        }
        set {
            this.supplierSubNoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.itek.de/Shop-Anbindung/Warenkorb/")]
public partial class typeOrderItem {
    
    private typeOrderItemItemChara itemCharaField;
    
    private bool itemCharaFieldSpecified;
    
    private typeRefItems refItemsField;
    
    private decimal eANField;
    
    private bool eANFieldSpecified;
    
    private string manufacturerIDField;
    
    private string manufacturerIDTypeField;
    
    private string artNoField;
    
    private decimal qtyField;
    
    private typeOrderItemQU quField;
    
    private string kurztextField;
    
    private string langtextField;
    
    private decimal offerPriceField;
    
    private bool offerPriceFieldSpecified;
    
    private decimal netPriceField;
    
    private bool netPriceFieldSpecified;
    
    private decimal priceBasisField;
    
    private bool priceBasisFieldSpecified;
    
    private decimal vATField;
    
    private bool vATFieldSpecified;
    
    private tgYesNo technClarificationField;
    
    private bool technClarificationFieldSpecified;
    
    private string hinweisField;
    
    private string fehlercodeField;
    
    private string fehlertextField;
    
    private decimal zuschlagField;
    
    private bool zuschlagFieldSpecified;
    
    private typeRohstoffanteil[] rohstoffanteilField;
    
    private bool diversField;
    
    private bool diversFieldSpecified;
    
    /// <remarks/>
    public typeOrderItemItemChara ItemChara {
        get {
            return this.itemCharaField;
        }
        set {
            this.itemCharaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ItemCharaSpecified {
        get {
            return this.itemCharaFieldSpecified;
        }
        set {
            this.itemCharaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public typeRefItems RefItems {
        get {
            return this.refItemsField;
        }
        set {
            this.refItemsField = value;
        }
    }
    
    /// <remarks/>
    public decimal EAN {
        get {
            return this.eANField;
        }
        set {
            this.eANField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EANSpecified {
        get {
            return this.eANFieldSpecified;
        }
        set {
            this.eANFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ManufacturerID {
        get {
            return this.manufacturerIDField;
        }
        set {
            this.manufacturerIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ManufacturerIDType {
        get {
            return this.manufacturerIDTypeField;
        }
        set {
            this.manufacturerIDTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ArtNo {
        get {
            return this.artNoField;
        }
        set {
            this.artNoField = value;
        }
    }
    
    /// <remarks/>
    public decimal Qty {
        get {
            return this.qtyField;
        }
        set {
            this.qtyField = value;
        }
    }
    
    /// <remarks/>
    public typeOrderItemQU QU {
        get {
            return this.quField;
        }
        set {
            this.quField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Kurztext {
        get {
            return this.kurztextField;
        }
        set {
            this.kurztextField = value;
        }
    }
    
    /// <remarks/>
    public string Langtext {
        get {
            return this.langtextField;
        }
        set {
            this.langtextField = value;
        }
    }
    
    /// <remarks/>
    public decimal OfferPrice {
        get {
            return this.offerPriceField;
        }
        set {
            this.offerPriceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OfferPriceSpecified {
        get {
            return this.offerPriceFieldSpecified;
        }
        set {
            this.offerPriceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal NetPrice {
        get {
            return this.netPriceField;
        }
        set {
            this.netPriceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool NetPriceSpecified {
        get {
            return this.netPriceFieldSpecified;
        }
        set {
            this.netPriceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal PriceBasis {
        get {
            return this.priceBasisField;
        }
        set {
            this.priceBasisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PriceBasisSpecified {
        get {
            return this.priceBasisFieldSpecified;
        }
        set {
            this.priceBasisFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal VAT {
        get {
            return this.vATField;
        }
        set {
            this.vATField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool VATSpecified {
        get {
            return this.vATFieldSpecified;
        }
        set {
            this.vATFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public tgYesNo TechnClarification {
        get {
            return this.technClarificationField;
        }
        set {
            this.technClarificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TechnClarificationSpecified {
        get {
            return this.technClarificationFieldSpecified;
        }
        set {
            this.technClarificationFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Hinweis {
        get {
            return this.hinweisField;
        }
        set {
            this.hinweisField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string Fehlercode {
        get {
            return this.fehlercodeField;
        }
        set {
            this.fehlercodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Fehlertext {
        get {
            return this.fehlertextField;
        }
        set {
            this.fehlertextField = value;
        }
    }
    
    /// <remarks/>
    public decimal Zuschlag {
        get {
            return this.zuschlagField;
        }
        set {
            this.zuschlagField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ZuschlagSpecified {
        get {
            return this.zuschlagFieldSpecified;
        }
        set {
            this.zuschlagFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Rohstoffanteil")]
    public typeRohstoffanteil[] Rohstoffanteil {
        get {
            return this.rohstoffanteilField;
        }
        set {
            this.rohstoffanteilField = value;
        }
    }
    
    /// <remarks/>
    public bool Divers {
        get {
            return this.diversField;
        }
        set {
            this.diversField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool DiversSpecified {
        get {
            return this.diversFieldSpecified;
        }
        set {
            this.diversFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.itek.de/Shop-Anbindung/Warenkorb/")]
public enum typeOrderItemItemChara {
    
    /// <remarks/>
    normal,
    
    /// <remarks/>
    alternate,
    
    /// <remarks/>
    provis,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.itek.de/Shop-Anbindung/Warenkorb/")]
public partial class typeOrderItemQU {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="normalizedString")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.itek.de/Shop-Anbindung/Warenkorb/")]
public enum tgYesNo {
    
    /// <remarks/>
    Yes,
    
    /// <remarks/>
    No,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.itek.de/Shop-Anbindung/Warenkorb/")]
public partial class typeDeliveryPlaceInfo {
    
    private string iDNoField;
    
    private typeAddress addressField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string IDNo {
        get {
            return this.iDNoField;
        }
        set {
            this.iDNoField = value;
        }
    }
    
    /// <remarks/>
    public typeAddress Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.itek.de/Shop-Anbindung/Warenkorb/")]
public partial class typeAddress {
    
    private string name1Field;
    
    private string name2Field;
    
    private string name3Field;
    
    private string name4Field;
    
    private string streetField;
    
    private string pCodeField;
    
    private string cityField;
    
    private string countryField;
    
    private string iLNField;
    
    private string contactField;
    
    private string phoneField;
    
    private string faxField;
    
    private string emailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Name1 {
        get {
            return this.name1Field;
        }
        set {
            this.name1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Name2 {
        get {
            return this.name2Field;
        }
        set {
            this.name2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Name3 {
        get {
            return this.name3Field;
        }
        set {
            this.name3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Name4 {
        get {
            return this.name4Field;
        }
        set {
            this.name4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Street {
        get {
            return this.streetField;
        }
        set {
            this.streetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string PCode {
        get {
            return this.pCodeField;
        }
        set {
            this.pCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ILN {
        get {
            return this.iLNField;
        }
        set {
            this.iLNField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Contact {
        get {
            return this.contactField;
        }
        set {
            this.contactField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Phone {
        get {
            return this.phoneField;
        }
        set {
            this.phoneField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Fax {
        get {
            return this.faxField;
        }
        set {
            this.faxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.itek.de/Shop-Anbindung/Warenkorb/")]
public partial class typeCustomerInfo {
    
    private string iDNoField;
    
    private typeAddress addressField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string IDNo {
        get {
            return this.iDNoField;
        }
        set {
            this.iDNoField = value;
        }
    }
    
    /// <remarks/>
    public typeAddress Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.itek.de/Shop-Anbindung/Warenkorb/")]
public partial class typeSupplierInfo {
    
    private string iDNoField;
    
    private typeAddress addressField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string IDNo {
        get {
            return this.iDNoField;
        }
        set {
            this.iDNoField = value;
        }
    }
    
    /// <remarks/>
    public typeAddress Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.itek.de/Shop-Anbindung/Warenkorb/")]
public partial class typeOrderInfo {
    
    private string inquiryNoField;
    
    private string offerNoField;
    
    private string partNoField;
    
    private string orderConfNoField;
    
    private object[] itemsField;
    
    private ItemsChoiceType[] itemsElementNameField;
    
    private typeOrderInfoModeOfShipment modeOfShipmentField;
    
    private string curField;
    
    private string zusatzTextField;
    
    private string kommissionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string InquiryNo {
        get {
            return this.inquiryNoField;
        }
        set {
            this.inquiryNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string OfferNo {
        get {
            return this.offerNoField;
        }
        set {
            this.offerNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string PartNo {
        get {
            return this.partNoField;
        }
        set {
            this.partNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string OrderConfNo {
        get {
            return this.orderConfNoField;
        }
        set {
            this.orderConfNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DeliveryDate", typeof(System.DateTime), DataType="date")]
    [System.Xml.Serialization.XmlElementAttribute("DeliveryWeek", typeof(string), DataType="positiveInteger")]
    [System.Xml.Serialization.XmlElementAttribute("DeliveryYear", typeof(string), DataType="integer")]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
    
    /// <remarks/>
    public typeOrderInfoModeOfShipment ModeOfShipment {
        get {
            return this.modeOfShipmentField;
        }
        set {
            this.modeOfShipmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Cur {
        get {
            return this.curField;
        }
        set {
            this.curField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string ZusatzText {
        get {
            return this.zusatzTextField;
        }
        set {
            this.zusatzTextField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString")]
    public string Kommission {
        get {
            return this.kommissionField;
        }
        set {
            this.kommissionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.itek.de/Shop-Anbindung/Warenkorb/", IncludeInSchema=false)]
public enum ItemsChoiceType {
    
    /// <remarks/>
    DeliveryDate,
    
    /// <remarks/>
    DeliveryWeek,
    
    /// <remarks/>
    DeliveryYear,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.itek.de/Shop-Anbindung/Warenkorb/")]
public enum typeOrderInfoModeOfShipment {
    
    /// <remarks/>
    Lieferung,
    
    /// <remarks/>
    Abholung,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.itek.de/Shop-Anbindung/Warenkorb/")]
public partial class typeOrder {
    
    private typeOrderInfo orderInfoField;
    
    private typeSupplierInfo supplierInfoField;
    
    private typeCustomerInfo customerInfoField;
    
    private typeDeliveryPlaceInfo deliveryPlaceInfoField;
    
    private typeOrderItem[] orderItemField;
    
    /// <remarks/>
    public typeOrderInfo OrderInfo {
        get {
            return this.orderInfoField;
        }
        set {
            this.orderInfoField = value;
        }
    }
    
    /// <remarks/>
    public typeSupplierInfo SupplierInfo {
        get {
            return this.supplierInfoField;
        }
        set {
            this.supplierInfoField = value;
        }
    }
    
    /// <remarks/>
    public typeCustomerInfo CustomerInfo {
        get {
            return this.customerInfoField;
        }
        set {
            this.customerInfoField = value;
        }
    }
    
    /// <remarks/>
    public typeDeliveryPlaceInfo DeliveryPlaceInfo {
        get {
            return this.deliveryPlaceInfoField;
        }
        set {
            this.deliveryPlaceInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OrderItem")]
    public typeOrderItem[] OrderItem {
        get {
            return this.orderItemField;
        }
        set {
            this.orderItemField = value;
        }
    }
}
